#!/bin/bash -e
CC=gcc
if hash colorgcc 2>/dev/null; then
	CC=colorgcc
fi
cstd='-std=gnu99'
CFLAGS="-Wall -Wextra -pedantic $cstd -pthread -fPIC -O2 -ffast-math -g $*"
libs='sdl2 gl freealut vorbisfile'
if ! hash pkg-config 2>/dev/null; then
	echo "pkg-config is missing" 1>&2
	exit 1
fi
CFLAGS="$CFLAGS $(pkg-config --cflags $libs)"
LDLIBS="$(pkg-config --libs $libs)"
LLIBS='-lSDL2_image -lSDL2_mixer -lpthread -lm'
CCM="$CC $cstd -MM"
cat <<'EOF'>.gitignore
.gitignore
*.tmp
# Make
Makefile
# CC
*.o
*.a
*.so
# VIM
*.vim
*.swp
# valgrind
*.valgrind
*.log
# archives
*.tgz
*.zip
EOF
cat <<EOF >Makefile
.PHONY: default clean

CC=$CC
CFLAGS=$CFLAGS
LDLIBS=$LDLIBS $LLIBS

EOF

printf "OBJECTS=" >>Makefile
for i in *.c; do
	printf ' \\\n\t%s' "${i/%.c/.o}" >>Makefile
done

cat <<'EOF' >>Makefile


default: libsmt.a libsmt.so $(DEMOS)
libsmt.a: $(OBJECTS)
	ar -cr libsmt.a $(OBJECTS)
libsmt.so: $(OBJECTS)
	$(CC) -shared -Wl,-soname,libsmt -o libsmt.so $(OBJECTS)
%.o: %.c
	$(CC) -c $< -o $@ $(CFLAGS)
clean:
	rm -f libsmt.a libsmt.so
	rm -f $(OBJECTS)
EOF
